<?php echo $this->doctype();?>
<html lang="pt">
<head>
<?php echo $this->headTitle();?>
<?php echo $this->headMeta();?>
<?php echo $this->headScript();?>
<?php echo $this->headLink();?>
<?php echo $this->JSHelper() ?> 
</head>
<body>
<?php echo $this->NavBar();?>

	<div class="container">
	<div id="flash-msg"></div>

     <?php echo $this->layout()->content; ?>

    </div>
	<!-- /container -->
<footer>&copy; <?= Zend_Date::now()->toString('YYYY');?> - Fernandes &amp; Terceiro, S.A.</footer>
</body>
</html>